version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
      - yarn global add @angular/cli
      - sudo apt install chromium-browser
  pre_build:
    commands:
      - export CHROME_BIN=chromium-browser
      - yarn
  build:
    commands:
      - ng test --single-run
      - ng build -prod
  post_build:
    commands:
      - aws s3 sync dist s3://moussypad.com --delete --acl public-read
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E10T16K5SZ532K --paths /*
